FROM alpine:latest

RUN apk update
RUN apk upgrade
RUN apk add --update iproute2 net-tools fping iputils-ping iputils-arping procps jq netcat-openbsd mtr musl libstdc++ libgcc

COPY code/pylon /usr/local/bin/
EXPOSE 443
EXPOSE 9993/udp
# ENV ZT_PYLON_SECRET_KEY=
# ENV ZT_PYLON_WHITELISTED_PORT=
ENTRYPOINT [ "/usr/local/bin/pylon" ]
CMD ["reflect"]
